### ISSUE TITLE
Offer option to embed a single graph on a website

### ISSUE THREAD

**Issue by ajRiverav** [jpadilla/tracking-status-pr#3]
I don't know the market *tracking-status-pr* is currently targeting, but news outlets would love to be able to embed a single table/graph in a report. There is a separate issue of where the data source is, but it can be solved by adding that the source is status.pr even though it is not affiliated with them.

**Comment by jpadilla** [comment]
@ajRiverav love this idea so much that I decided to work on a first iteration now. Every stat now has an embed link which will pop up a modal with instructions. Check it out: https://statuspr.jpadilla.com

**Comment by jpadilla** [comment]
Demo: http://jsbin.com/wayiguwizi/edit?html,output
