### ISSUE TITLE
Bank Branches units issue

### ISSUE THREAD

**Issue by ajRiverav** [jpadilla/tracking-status-pr#5]
The first data point (Oct. 02) in Bank Branches' plot has the wrong units. It seems to be in number of branches, whereas the rest of the data points are in percentage. 

<script src="https://statuspr.jpadilla.com/embed.js" data-stat="bank"></script>

**Comment by jpadilla** [comment]
Fixed. Updated that data point to 48.72% based on 153 branches out of 314. Thanks for reporting!

**Comment by ajRiverav** [comment]
Supermarkets' plot has the same issue w/ first two points. 
@jpadilla 
I don't want to open a new issue just for this...

**Comment by jpadilla** [comment]
@ajRiverav Fixed!
