### ISSUE TITLE
typo in disclaimer

### ISSUE THREAD

**Issue by ajRiverav** [jpadilla/tracking-status-pr#6]
Disclaimer should read "affiliated WITH" vs "affiliated to".

https://books.google.com/ngrams/graph?content=affiliated+with%2Caffiliated+to&year_start=1800&year_end=2000&corpus=17&smoothing=3&share=&direct_url=t1%3B%2Caffiliated%20with%3B%2Cc0%3B.t1%3B%2Caffiliated%20to%3B%2Cc0

**Comment by jpadilla** [comment]
@ajRiverav thanks!
